# Generated by Django 6.0.7 on 2026-07-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FootballPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(choices=[('GK', 'GK'), ('RB', 'RB'), ('CB', 'CB'), ('LB', 'LB'), ('CDM', 'CDM'), ('CM', 'CM'), ('CAM', 'CAM'), ('RW', 'RW'), ('ST', 'ST'), ('LW', 'LW')], max_length=3)),
                ('imge', models.ImageField(upload_to='players/')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
