# Generated by Django 6.0.7 on 2026-07-13 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FootballPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(choices=[('GK', 'GK'), ('RB', 'RB'), ('CB', 'CB'), ('LB', 'LB'), ('CDM', 'CDM'), ('CM', 'CM'), ('CAM', 'CAM'), ('RW', 'RW'), ('ST', 'ST'), ('LW', 'LW')], max_length=3)),
                ('image', models.ImageField(upload_to='players/')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_one_name', models.CharField(max_length=50)),
                ('player_two_name', models.CharField(max_length=50)),
                ('game_mode', models.CharField(choices=[('S', 'Single'), ('L', 'Local')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_owner', models.CharField(choices=[('P1', 'Player One'), ('P2', 'Player Two')], max_length=2)),
                ('is_visible_selected', models.BooleanField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='GamePlay.game')),
                ('hidden_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_picks', to='GamePlay.footballplayer')),
                ('visible_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visible_picks', to='GamePlay.footballplayer')),
            ],
        ),
    ]
